first_project:
  outputs:
    dev:
      dataset: newyork_taxi
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: warm-particle-307005
      threads: 4
      type: bigquery
  target: dev